version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: mikro-orm-db
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=mikro_orm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
volumes:
  data:
    name: db_data